### ISSUE TITLE
change subtitle error

### ISSUE THREAD

**Issue by PeteSSMMSS** [Naam/paperless-alfred#1]
wonderful woprkflow for alfred! thanks for your work! I want to change it a bit, instead of the archive_serial_number in the subtitle, i want to display correspondent, but when i change Line 74 to 

` asn = result['correspondent'] or "None"`

it somehow displays only a number instead of the correspondent (maybe the count of characters?) how can I fix this? thanks in advance!

**Comment by Naam** [comment]
It's not necessarily clear in the Paperless documentation.

First they say:
> correspondent: Correspondent of this document or null.

Then in the POST section (emphasis mine):

> correspondent: Specify **the ID** of a correspondent that the consumer should use for the document.
https://docs.paperless-ngx.com/api/

So ultimately, I think the correspondent is only available as an ID as part of the API documentation.

Let me know if we can close the issue

**Comment by Naam** [comment]
I have found a way to do what you want, though. A dictionary of correspondents can be retrieved at the following endpoint:
http://your-instance:port/api/correspondents/

By parsing it one can retrieve the `name` field, which seems to be the properly formatted one, for a given `id`.
I wanted to keep the plugin fast, would be nice to cache it too or verify it doesn't hinder performance since it's one additional API call per item in the result list.

**Comment by Naam** [comment]
I've created a pull request if you want to try it out and see if it works for you. It did on my setup.

If it does, I'll merge it to main branch and close this. Feel free to comment on it if you think anything can be done in a better way.

Cheers.
